### ISSUE TITLE
Broken with python3

### ISSUE THREAD

**Issue by cclements** [mnagel/clustergit#28]
```
python2 ./clustergit
Starting git status...
Scanning sub directories of .
Error: None of those sub directories had a .git file.

python3 ./clustergit
  File "./clustergit", line 269
    except subprocess.CalledProcessError, e:
                                        ^
SyntaxError: invalid syntax
```

**Comment by cclements** [comment]
Thanks for the fast response, but it appears I still experience issues with python3:

```
python2 /usr/local/bin/clustergit
Starting git status...
Scanning sub directories of .
./clustergit                            : Clean
Done


python3 /usr/local/bin/clustergit
Starting git status...
Scanning sub directories of .
Traceback (most recent call last):
  File "/usr/local/bin/clustergit", line 513, in <module>
    main(sys.argv[1:])
  File "/usr/local/bin/clustergit", line 492, in main
    new_gitted, new_dirties = check(path, options)
  File "/usr/local/bin/clustergit", line 344, in check
    if len(options.branch) > 0 and 'On branch ' + options.branch not in out:
TypeError: a bytes-like object is required, not 'str'
```

**Comment by mnagel** [comment]
Please have a look at ce875fc571112e50232c5c884d69814501ffe46f

**Comment by cclements** [comment]
working great again, thanks!
