### ISSUE TITLE
_ctypes module not found

### ISSUE THREAD

**Issue by defaltus** [mnagel/clustergit#48]
ImportError when Clustergit is run from cmd.

```
Traceback (most recent call last):
  File "C:\CS\clustergit", line 20, in <module>
    from ctypes import windll, c_ulong
  File "C:\python\lib\ctypes\__init__.py", line 8, in <module>
    from _ctypes import Union, Structure, Array
ImportError: DLL load failed while importing _ctypes: The specified module was not found.
```

Tried reinstalling mambaforge, error still there. My system:
- Python 3.10 (recent mambaforge)
- Windows 11

**Comment by defaltus** [comment]
Found a corrputed python3.dll in my path which was causing the error.
